
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: mini-youtube-db
    environment:
      POSTGRES_USER: wesley
      POSTGRES_PASSWORD: R51VUl9NPj4g
      POSTGRES_DB: mini-youtube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
