name: ci-cd
on:
  push: { branches: [main] }
jobs:
  build-deploy:
    permissions: { contents: read, id-token: write }
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth' uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: 'gh-automation@$PROJECT_ID.iam.gserviceaccount.com'
        project_id: '${{ secrets.PROJECT_ID }}'
        access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/iam'
    - uses: 'google-github-actions/setup-gcloud@v2'
    - run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/mini-youtube-api:$GITHUB_SHA backend/
        gcloud run deploy mini-youtube-api \
          --image gcr.io/$PROJECT_ID/mini-youtube-api:$GITHUB_SHA \
          --region=$REGION \
          --quiet
